version: 0.2

phases:
  build:
    commands:   
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -backend=false
      - terraform fmt --recursive --check

  post_build:
    commands:
      - echo "tflint complete"
