version: 0.2

phases:
  build:
    commands:   
      - cd "$CODEBUILD_SRC_DIR"
      - |
        if [ -z "${CHECKOV_SKIPS}" ]; then 
          checkov --directory ./ --skip-path ./deploy -o junitxml > checkov.xml
        else
          checkov --directory ./ --skip-path ./deploy --skip-check ${CHECKOV_SKIPS} -o junitxml > checkov.xml
        fi

      - cat checkov.xml

  post_build:
    commands:
      - echo "checkov complete, see report for details"

reports:
  ${SAST_REPORT_ARN}:
    files:
      - checkov.xml
    base-directory: ./
    file-format: JUNITXML
      
